CREATE TABLE USER (
    Uid INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE "GROUP" (
    Gid INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    GroupName TEXT NOT NULL
);

CREATE TABLE SUBGROUP (
    SGid INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    SubGroupName TEXT NOT NULL,
    Gid INTEGER NOT NULL,
    FOREIGN KEY (Gid) REFERENCES "GROUP"(Gid)
);

CREATE TABLE USER_GROUP (
    Uid INTEGER NOT NULL,
    Gid INTEGER NOT NULL,
    SGid INTEGER,
    PRIMARY KEY (Uid, Gid),
    FOREIGN KEY (Uid) REFERENCES USER(Uid),
    FOREIGN KEY (Gid) REFERENCES "GROUP"(Gid),
    FOREIGN KEY (SGid) REFERENCES SUBGROUP(SGid)
);